FORMAT: 1A
HOST: https://private-2686f-spacemission.apiary-mock.com/

# SpaceMission

SpaceMission is an API for astronaut food tracking prototype application.

## Food list [/food]

### List of available food [GET]

Returns a list of food available on a space mission.

+ Response 200 (application/json)

        {
         "status": 0,
         "message": "",
         "data": [{
          "name": "Fruit",
          "children": [{
           "name": "Grapefruit",
           "code": 1,
           "vitamins": [1,
           2,
           3]
          },
          {
           "name": "Guava",
           "code": 2,
           "vitamins": [1,
           2,
           3,
           5]
          },
          {
           "name": "Mango",
           "code": 3,
           "vitamins": [1,
           2,
           3,
           5]
          },
          {
           "name": "Papaya",
           "code": 4,
           "vitamins": [1,
           3,
           5]
          },
          {
           "name": "Passionfruit",
           "code": 5,
           "vitamins": [1,
           3]
          },
          {
           "name": "Tomatoes",
           "code": 6,
           "vitamins": [1]
          },
          {
           "name": "Avocado",
           "code": 7,
           "vitamins": [2,
           5]
          },
          {
           "name": "Orange",
           "code": 8,
           "vitamins": [2,
           3]
          },
          {
           "name": "Dates",
           "code": 9,
           "vitamins": [2]
          },
          {
           "name": "Strawberries",
           "code": 10,
           "vitamins": [3]
          }]
         },
         {
          "name": "Vegetables",
          "children": [{
           "name": "Broccoli",
           "code": 11,
           "vitamins": [1,
           3]
          },
          {
           "name": "Carrots",
           "code": 12,
           "vitamins": [1]
          },
          {
           "name": "Peas",
           "code": 13,
           "vitamins": [1,
           2]
          },
          {
           "name": "Pumpkin",
           "code": 14,
           "vitamins": [1,
           5]
          },
          {
           "name": "Spinach",
           "code": 15,
           "vitamins": [1]
          },
          {
           "name": "Corn",
           "code": 17,
           "vitamins": [2]
          },
          {
           "name": "Potatoe",
           "code": 18,
           "vitamins": [2,
           5]
          },
          {
           "name": "Scarce",
           "children": [{
            "name": "Asparagu",
            "code": 16,
            "vitamins": [2]
           },
           {
            "name": "Mushrooms",
            "code": 19,
            "vitamins": [4]
           }]
          }]
         },
         {
          "name": "Nut/Grain",
          "children": [{
           "name": " Chestnuts  ",
           "code": 20,
           "vitamins": [1,
           2,
           3]
          },
          {
           "name": "Pecans ",
           "code": 21,
           "vitamins": [1,
           2]
          },
          {
           "name": "Pistachios",
           "code": 22,
           "vitamins": [1,
           2]
          },
          {
           "name": "Peanuts",
           "code": 23,
           "vitamins": [2]
          },
          {
           "name": "Almonds ",
           "code": 24,
           "vitamins": [5]
          }]
         }]
        }

  
## Daily food intake [/dailyintake]

### Record daily food intake [POST]

Stores information about daily food intake. 

+ Attributes
    + date: `2034-02-13` (string) - Current Earth date 
    + dailyIntake: [[1, 4, 12],[1,0,4],[1,2,0]] (string) - 2D array. First row contains 'code' identifiers of consumed food (Grapefruit, Papaya and Carrot in provided example), other rows contain quantity information for each meal.


+ Request (application/json)

        {
            "date": "2074-02-13",
            "dailyIntake": [[1, 4, 12],[1,0,4],[1,2,0]]
        }

+ Response 200 (application/json)

    + Headers

            Location: /dailyintake

    + Body

            {
                "status": 0,
                "message": "",
                "data": null
            }
## Sunday Vitamins Collection [/dailyvitamins/1]

### List vitamins for Sunday [GET]

Returns a list of recommended vitamins for Sunday.


+ Response 200 (application/json)

        {
          "status": 0,
          "message": "",
          "data": [{
            "name": "A",
            "code": 1
          },
          {
            "name": "B1",
            "code": 2
          },
          {
            "name": "C",
            "code": 3
          }]
        }

## Monday Vitamins Collection [/dailyvitamins/2]

### List vitamins for Monday [GET] 

+ Response 400 (application/json)

        {
          "status": 55,
          "message": "Unable to read data for specified day",
          "data": null
        }


## Tuesday Vitamins Collection [/dailyvitamins/3]

### List vitamins for Tuesday [GET]

+ Response 200 (application/json)

        {
          "status": 0,
          "message": "",
          "data": [{
            "name": "A",
            "code": 1
          },{
            "name": "E",
            "code": 5
          }]
        }
        
## Wednesday Vitamins Collection [/dailyvitamins/4]

### List vitamins for Wednesday [GET]

+ Response 200 (application/json)

        {
          "status": 0,
          "message": "",
          "data": [
          {
          "name": "B1",
          "code": 2
          },
          {
          "name": "C",
          "code": 3
          },
          {
          "name": "D",
          "code": 4
          }]
        }
        
## Thusday Vitamins Collection [/dailyvitamins/5]
        
              
### List vitamins for Thusday [GET]

+ Response 200 (application/json)

        {
          "status": 0,
          "message": "",
          "data": [
          {
            "name": "D",
            "code": 4
          },{
            "name": "E",
            "code": 5
          }]
        }
        
## Friday Vitamins Collection [/dailyvitamins/6]
        
### List vitamins for Friday [GET]

+ Response 200 (application/json)

        {
          "status": 0,
          "message": "",
          "data": [{
            "name": "A",
            "code": 1
          },{
            "name": "E",
            "code": 5
          }]
        }
        
## Saturday Vitamins Collection [/dailyvitamins/7]
        
### List vitamins for Saturday [GET]

+ Response 200 (application/json)

        {
          "status": 0,
          "message": "",
          "data": [{
            "name": "A",
            "code": 1daiz
          },
          {
            "name": "B1",
            "code": 2
          },
          {
            "name": "C",
            "code": 3
          },
          {
            "name": "D",
            "code": 4
          },{
            "name": "E",
            "code": 5
          }]
        }